#
# Copyright (c) 2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/aria2-builder
#

name: Aria2 Builder

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PLATFORMS: [amd64, arm64, armhf, i386]
        include:
        - PLATFORMS: amd64
          BUILDER_IMAGE: debian:testing
          BUILD_SCRIPT: aria2-gnu-linux-build.sh
        - PLATFORMS: arm64
          BUILDER_IMAGE: debian:testing
          BUILD_SCRIPT: aria2-gnu-linux-cross-build-arm64.sh
        - PLATFORMS: armhf
          BUILDER_IMAGE: ubuntu:14.04
          BUILD_SCRIPT: aria2-gnu-linux-cross-build-armhf.sh
        - PLATFORMS: i386
          BUILDER_IMAGE: debian:testing
          BUILD_SCRIPT: aria2-gnu-linux-cross-build-i386.sh

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      env:
        DOCKER_BUILDKIT: 1
        BUILDER_IMAGE: ${{ matrix.BUILDER_IMAGE }}
        BUILD_SCRIPT: ${{ matrix.BUILD_SCRIPT }}
      run: |
        docker build \
          --build-arg BUILDER_IMAGE \
          --build-arg BUILD_SCRIPT \
          --platform=local \
          -o ./output .

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: aria2-${{ matrix.PLATFORMS }}
        path: output
